# Generated by Django 4.2.4 on 2024-04-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45)),
                ('description', models.CharField(blank=True, max_length=105, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('imgPath', models.ImageField(blank=True, upload_to='movies/images')),
                ('duration', models.IntegerField(blank=True)),
                ('language', models.CharField(blank=True, max_length=45)),
                ('mpaaRating', models.JSONField(blank=True)),
                ('userRating', models.IntegerField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='gvcinema.genre')),
            ],
        ),
    ]
