# Generated by Django 4.2.4 on 2024-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvcinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imgPath',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
    ]
