# Generated by Django 4.2.4 on 2024-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvcinema', '0002_alter_movie_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=45),
        ),
    ]
